import { z } from "zod";
export declare const TierSchema: z.ZodEnum<["exec", "director", "manager", "associate", "intern", "bot"]>;
export type Tier = z.infer<typeof TierSchema>;
export declare const ModelTierSchema: z.ZodEnum<["sonnet", "haiku", "opus"]>;
export type ModelTier = z.infer<typeof ModelTierSchema>;
export declare const Big5Schema: z.ZodObject<{
    openness: z.ZodNumber;
    conscientiousness: z.ZodNumber;
    extraversion: z.ZodNumber;
    agreeableness: z.ZodNumber;
    neuroticism: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    openness: number;
    conscientiousness: number;
    extraversion: number;
    agreeableness: number;
    neuroticism: number;
}, {
    openness: number;
    conscientiousness: number;
    extraversion: number;
    agreeableness: number;
    neuroticism: number;
}>;
export type Big5 = z.infer<typeof Big5Schema>;
export declare const PersonalitySchema: z.ZodObject<{
    big5: z.ZodObject<{
        openness: z.ZodNumber;
        conscientiousness: z.ZodNumber;
        extraversion: z.ZodNumber;
        agreeableness: z.ZodNumber;
        neuroticism: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        openness: number;
        conscientiousness: number;
        extraversion: number;
        agreeableness: number;
        neuroticism: number;
    }, {
        openness: number;
        conscientiousness: number;
        extraversion: number;
        agreeableness: number;
        neuroticism: number;
    }>;
    archetype: z.ZodString;
    quirks: z.ZodArray<z.ZodString, "many">;
    voiceExamples: z.ZodArray<z.ZodString, "many">;
}, "strip", z.ZodTypeAny, {
    big5: {
        openness: number;
        conscientiousness: number;
        extraversion: number;
        agreeableness: number;
        neuroticism: number;
    };
    archetype: string;
    quirks: string[];
    voiceExamples: string[];
}, {
    big5: {
        openness: number;
        conscientiousness: number;
        extraversion: number;
        agreeableness: number;
        neuroticism: number;
    };
    archetype: string;
    quirks: string[];
    voiceExamples: string[];
}>;
export type Personality = z.infer<typeof PersonalitySchema>;
export declare const AgentSchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    name: z.ZodString;
    role: z.ZodString;
    department: z.ZodNullable<z.ZodString>;
    tier: z.ZodEnum<["exec", "director", "manager", "associate", "intern", "bot"]>;
    manager_id: z.ZodNullable<z.ZodString>;
    reports_to_ceo: z.ZodBoolean;
    personality: z.ZodObject<{
        big5: z.ZodObject<{
            openness: z.ZodNumber;
            conscientiousness: z.ZodNumber;
            extraversion: z.ZodNumber;
            agreeableness: z.ZodNumber;
            neuroticism: z.ZodNumber;
        }, "strip", z.ZodTypeAny, {
            openness: number;
            conscientiousness: number;
            extraversion: number;
            agreeableness: number;
            neuroticism: number;
        }, {
            openness: number;
            conscientiousness: number;
            extraversion: number;
            agreeableness: number;
            neuroticism: number;
        }>;
        archetype: z.ZodString;
        quirks: z.ZodArray<z.ZodString, "many">;
        voiceExamples: z.ZodArray<z.ZodString, "many">;
    }, "strip", z.ZodTypeAny, {
        big5: {
            openness: number;
            conscientiousness: number;
            extraversion: number;
            agreeableness: number;
            neuroticism: number;
        };
        archetype: string;
        quirks: string[];
        voiceExamples: string[];
    }, {
        big5: {
            openness: number;
            conscientiousness: number;
            extraversion: number;
            agreeableness: number;
            neuroticism: number;
        };
        archetype: string;
        quirks: string[];
        voiceExamples: string[];
    }>;
    background: z.ZodNullable<z.ZodString>;
    frozen_core: z.ZodString;
    manager_overlay: z.ZodString;
    learned_addendum: z.ZodString;
    allowed_tools: z.ZodArray<z.ZodString, "many">;
    model_tier: z.ZodEnum<["sonnet", "haiku", "opus"]>;
    status: z.ZodEnum<["active", "paused", "terminated"]>;
    daily_token_budget: z.ZodNumber;
    tokens_used_today: z.ZodNumber;
    addendum_loop_active: z.ZodDefault<z.ZodBoolean>;
    chatter_posts_today: z.ZodDefault<z.ZodNumber>;
    last_reset_company_date: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    last_reflection_at: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    tool_access: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    mcp_access: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    always_on: z.ZodDefault<z.ZodBoolean>;
    in_standup: z.ZodDefault<z.ZodBoolean>;
    is_human: z.ZodDefault<z.ZodBoolean>;
    tic: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    fallback_agent_id: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    created_at: z.ZodString;
    updated_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    status: "active" | "paused" | "terminated";
    id: string;
    tenant_id: string;
    name: string;
    role: string;
    department: string | null;
    tier: "exec" | "director" | "manager" | "associate" | "intern" | "bot";
    manager_id: string | null;
    reports_to_ceo: boolean;
    personality: {
        big5: {
            openness: number;
            conscientiousness: number;
            extraversion: number;
            agreeableness: number;
            neuroticism: number;
        };
        archetype: string;
        quirks: string[];
        voiceExamples: string[];
    };
    background: string | null;
    frozen_core: string;
    manager_overlay: string;
    learned_addendum: string;
    allowed_tools: string[];
    model_tier: "sonnet" | "haiku" | "opus";
    daily_token_budget: number;
    tokens_used_today: number;
    addendum_loop_active: boolean;
    chatter_posts_today: number;
    last_reset_company_date: string | null;
    last_reflection_at: string | null;
    tool_access: string[];
    mcp_access: string[];
    always_on: boolean;
    in_standup: boolean;
    is_human: boolean;
    tic: string | null;
    fallback_agent_id: string | null;
    created_at: string;
    updated_at: string;
}, {
    status: "active" | "paused" | "terminated";
    id: string;
    tenant_id: string;
    name: string;
    role: string;
    department: string | null;
    tier: "exec" | "director" | "manager" | "associate" | "intern" | "bot";
    manager_id: string | null;
    reports_to_ceo: boolean;
    personality: {
        big5: {
            openness: number;
            conscientiousness: number;
            extraversion: number;
            agreeableness: number;
            neuroticism: number;
        };
        archetype: string;
        quirks: string[];
        voiceExamples: string[];
    };
    background: string | null;
    frozen_core: string;
    manager_overlay: string;
    learned_addendum: string;
    allowed_tools: string[];
    model_tier: "sonnet" | "haiku" | "opus";
    daily_token_budget: number;
    tokens_used_today: number;
    created_at: string;
    updated_at: string;
    addendum_loop_active?: boolean | undefined;
    chatter_posts_today?: number | undefined;
    last_reset_company_date?: string | null | undefined;
    last_reflection_at?: string | null | undefined;
    tool_access?: string[] | undefined;
    mcp_access?: string[] | undefined;
    always_on?: boolean | undefined;
    in_standup?: boolean | undefined;
    is_human?: boolean | undefined;
    tic?: string | null | undefined;
    fallback_agent_id?: string | null | undefined;
}>;
export type Agent = z.infer<typeof AgentSchema>;
export declare const ForumPostSchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    channel: z.ZodString;
    author_id: z.ZodString;
    parent_id: z.ZodNullable<z.ZodString>;
    body: z.ZodString;
    metadata: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    created_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    tenant_id: string;
    created_at: string;
    channel: string;
    author_id: string;
    parent_id: string | null;
    body: string;
    metadata: Record<string, unknown>;
}, {
    id: string;
    tenant_id: string;
    created_at: string;
    channel: string;
    author_id: string;
    parent_id: string | null;
    body: string;
    metadata: Record<string, unknown>;
}>;
export type ForumPost = z.infer<typeof ForumPostSchema>;
export declare const DmSchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    from_id: z.ZodString;
    to_id: z.ZodString;
    body: z.ZodString;
    read_at: z.ZodNullable<z.ZodString>;
    in_flight_since: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    created_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    tenant_id: string;
    created_at: string;
    body: string;
    from_id: string;
    to_id: string;
    read_at: string | null;
    in_flight_since: string | null;
}, {
    id: string;
    tenant_id: string;
    created_at: string;
    body: string;
    from_id: string;
    to_id: string;
    read_at: string | null;
    in_flight_since?: string | null | undefined;
}>;
export type Dm = z.infer<typeof DmSchema>;
export declare const ProposalStatusSchema: z.ZodEnum<["pending", "approved", "rejected", "applied"]>;
export type ProposalStatus = z.infer<typeof ProposalStatusSchema>;
export declare const PromptEvolutionEntrySchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    agent_id: z.ZodString;
    old_value: z.ZodNullable<z.ZodString>;
    new_value: z.ZodNullable<z.ZodString>;
    reason: z.ZodNullable<z.ZodString>;
    proposed_by: z.ZodString;
    status: z.ZodEnum<["pending", "approved", "rejected", "applied"]>;
    reviewed_by_ceo_at: z.ZodNullable<z.ZodString>;
    created_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    status: "pending" | "approved" | "rejected" | "applied";
    id: string;
    tenant_id: string;
    created_at: string;
    agent_id: string;
    old_value: string | null;
    new_value: string | null;
    reason: string | null;
    proposed_by: string;
    reviewed_by_ceo_at: string | null;
}, {
    status: "pending" | "approved" | "rejected" | "applied";
    id: string;
    tenant_id: string;
    created_at: string;
    agent_id: string;
    old_value: string | null;
    new_value: string | null;
    reason: string | null;
    proposed_by: string;
    reviewed_by_ceo_at: string | null;
}>;
export type PromptEvolutionEntry = z.infer<typeof PromptEvolutionEntrySchema>;
export declare const KNOWN_MCP_SERVERS: readonly ["alai"];
export type KnownMcpServer = (typeof KNOWN_MCP_SERVERS)[number];
export declare const KNOWN_TOOL_NAMES: readonly ["web_search", "code_artifact_create", "markdown_artifact_create", "calendar_read", "image_generate", "dm_send", "roster_lookup", "project_create", "project_post", "commitment_create", "imagen_generate", "read_artifact", "project_complete", "code_execution", "browser_fetch_text", "browser_extract_links", "browser_screenshot"];
export type KnownToolName = (typeof KNOWN_TOOL_NAMES)[number];
export declare const Channels: {
    readonly ANNOUNCEMENTS: "announcements";
    readonly GENERAL: "general";
    readonly WATERCOOLER: "watercooler";
    readonly STANDUP: "standup";
    readonly CEO_BRIEF: "ceo-brief";
};
export type Channel = (typeof Channels)[keyof typeof Channels];
export declare const COST_PER_M_TOKENS: {
    readonly sonnet: {
        readonly input_fresh: 3;
        readonly input_cached: 0.3;
        readonly output: 15;
    };
    readonly haiku: {
        readonly input_fresh: 1;
        readonly input_cached: 0.1;
        readonly output: 5;
    };
    readonly opus: {
        readonly input_fresh: 5;
        readonly input_cached: 0.5;
        readonly output: 25;
    };
};
export declare const ReportSchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    ritual_name: z.ZodString;
    agent_id: z.ZodString;
    title: z.ZodString;
    body: z.ZodString;
    company_date: z.ZodString;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    created_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    tenant_id: string;
    created_at: string;
    body: string;
    metadata: Record<string, unknown>;
    agent_id: string;
    ritual_name: string;
    title: string;
    company_date: string;
}, {
    id: string;
    tenant_id: string;
    created_at: string;
    body: string;
    agent_id: string;
    ritual_name: string;
    title: string;
    company_date: string;
    metadata?: Record<string, unknown> | undefined;
}>;
export type Report = z.infer<typeof ReportSchema>;
export declare const ReportRunSchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    ritual_name: z.ZodString;
    last_run_at: z.ZodNullable<z.ZodString>;
    last_run_company_date: z.ZodNullable<z.ZodString>;
    next_run_at: z.ZodString;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    created_at: z.ZodString;
    updated_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    tenant_id: string;
    created_at: string;
    updated_at: string;
    metadata: Record<string, unknown>;
    ritual_name: string;
    last_run_at: string | null;
    last_run_company_date: string | null;
    next_run_at: string;
}, {
    id: string;
    tenant_id: string;
    created_at: string;
    updated_at: string;
    ritual_name: string;
    last_run_at: string | null;
    last_run_company_date: string | null;
    next_run_at: string;
    metadata?: Record<string, unknown> | undefined;
}>;
export type ReportRun = z.infer<typeof ReportRunSchema>;
export declare const DepartmentSchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    slug: z.ZodString;
    display_name: z.ZodString;
    description: z.ZodNullable<z.ZodString>;
    display_order: z.ZodNumber;
    head_agent_id: z.ZodNullable<z.ZodString>;
    created_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    tenant_id: string;
    created_at: string;
    slug: string;
    display_name: string;
    description: string | null;
    display_order: number;
    head_agent_id: string | null;
}, {
    id: string;
    tenant_id: string;
    created_at: string;
    slug: string;
    display_name: string;
    description: string | null;
    display_order: number;
    head_agent_id: string | null;
}>;
export type Department = z.infer<typeof DepartmentSchema>;
export declare const ArtifactContentTypeSchema: z.ZodEnum<["markdown", "plaintext", "code"]>;
export type ArtifactContentType = z.infer<typeof ArtifactContentTypeSchema>;
export declare const ArtifactStatusSchema: z.ZodEnum<["draft", "accepted", "rejected", "superseded"]>;
export type ArtifactStatus = z.infer<typeof ArtifactStatusSchema>;
export declare const ArtifactSchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    agent_id: z.ZodString;
    title: z.ZodString;
    summary: z.ZodNullable<z.ZodString>;
    content_type: z.ZodEnum<["markdown", "plaintext", "code"]>;
    language: z.ZodNullable<z.ZodString>;
    file_path: z.ZodString;
    size_bytes: z.ZodNumber;
    parent_artifact_id: z.ZodNullable<z.ZodString>;
    version: z.ZodNumber;
    status: z.ZodEnum<["draft", "accepted", "rejected", "superseded"]>;
    triggered_by_dm_id: z.ZodNullable<z.ZodString>;
    triggered_by_post_id: z.ZodNullable<z.ZodString>;
    created_at: z.ZodString;
    accepted_at: z.ZodNullable<z.ZodString>;
    accepted_by: z.ZodNullable<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "rejected" | "draft" | "accepted" | "superseded";
    id: string;
    tenant_id: string;
    created_at: string;
    agent_id: string;
    title: string;
    summary: string | null;
    content_type: "code" | "markdown" | "plaintext";
    language: string | null;
    file_path: string;
    size_bytes: number;
    parent_artifact_id: string | null;
    version: number;
    triggered_by_dm_id: string | null;
    triggered_by_post_id: string | null;
    accepted_at: string | null;
    accepted_by: string | null;
}, {
    status: "rejected" | "draft" | "accepted" | "superseded";
    id: string;
    tenant_id: string;
    created_at: string;
    agent_id: string;
    title: string;
    summary: string | null;
    content_type: "code" | "markdown" | "plaintext";
    language: string | null;
    file_path: string;
    size_bytes: number;
    parent_artifact_id: string | null;
    version: number;
    triggered_by_dm_id: string | null;
    triggered_by_post_id: string | null;
    accepted_at: string | null;
    accepted_by: string | null;
}>;
export type Artifact = z.infer<typeof ArtifactSchema>;
export declare const AgentCredentialSchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    agent_id: z.ZodString;
    provider: z.ZodString;
    scope: z.ZodString;
    access_token: z.ZodString;
    refresh_token: z.ZodNullable<z.ZodString>;
    expires_at: z.ZodNullable<z.ZodString>;
    granted_by: z.ZodString;
    granted_at: z.ZodString;
    last_used_at: z.ZodNullable<z.ZodString>;
    use_count: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    id: string;
    tenant_id: string;
    agent_id: string;
    provider: string;
    scope: string;
    access_token: string;
    refresh_token: string | null;
    expires_at: string | null;
    granted_by: string;
    granted_at: string;
    last_used_at: string | null;
    use_count: number;
}, {
    id: string;
    tenant_id: string;
    agent_id: string;
    provider: string;
    scope: string;
    access_token: string;
    refresh_token: string | null;
    expires_at: string | null;
    granted_by: string;
    granted_at: string;
    last_used_at: string | null;
    use_count: number;
}>;
export type AgentCredential = z.infer<typeof AgentCredentialSchema>;
export declare const RealActionAuditSchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    agent_id: z.ZodString;
    tool_name: z.ZodString;
    arguments_json: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    result_summary: z.ZodNullable<z.ZodString>;
    result_full_json: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    success: z.ZodBoolean;
    error_message: z.ZodNullable<z.ZodString>;
    duration_ms: z.ZodNullable<z.ZodNumber>;
    triggered_by_dm_id: z.ZodNullable<z.ZodString>;
    created_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    tenant_id: string;
    created_at: string;
    agent_id: string;
    triggered_by_dm_id: string | null;
    tool_name: string;
    arguments_json: Record<string, unknown>;
    result_summary: string | null;
    result_full_json: Record<string, unknown> | null;
    success: boolean;
    error_message: string | null;
    duration_ms: number | null;
}, {
    id: string;
    tenant_id: string;
    created_at: string;
    agent_id: string;
    triggered_by_dm_id: string | null;
    tool_name: string;
    arguments_json: Record<string, unknown>;
    result_summary: string | null;
    result_full_json: Record<string, unknown> | null;
    success: boolean;
    error_message: string | null;
    duration_ms: number | null;
}>;
export type RealActionAudit = z.infer<typeof RealActionAuditSchema>;
export declare const ProjectStatusSchema: z.ZodEnum<["active", "completed", "cancelled"]>;
export type ProjectStatus = z.infer<typeof ProjectStatusSchema>;
export declare const ProjectSchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    title: z.ZodString;
    description: z.ZodString;
    status: z.ZodEnum<["active", "completed", "cancelled"]>;
    created_by: z.ZodNullable<z.ZodString>;
    created_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    status: "active" | "completed" | "cancelled";
    id: string;
    tenant_id: string;
    created_at: string;
    title: string;
    description: string;
    created_by: string | null;
}, {
    status: "active" | "completed" | "cancelled";
    id: string;
    tenant_id: string;
    created_at: string;
    title: string;
    description: string;
    created_by: string | null;
}>;
export type Project = z.infer<typeof ProjectSchema>;
export declare const ProjectMemberSchema: z.ZodObject<{
    project_id: z.ZodString;
    agent_id: z.ZodString;
    added_at: z.ZodString;
    added_by: z.ZodNullable<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    agent_id: string;
    project_id: string;
    added_at: string;
    added_by: string | null;
}, {
    agent_id: string;
    project_id: string;
    added_at: string;
    added_by: string | null;
}>;
export type ProjectMember = z.infer<typeof ProjectMemberSchema>;
export declare const ProjectMessageTypeSchema: z.ZodEnum<["message", "artifact", "system"]>;
export type ProjectMessageType = z.infer<typeof ProjectMessageTypeSchema>;
export declare const ProjectMessageSchema: z.ZodObject<{
    id: z.ZodString;
    project_id: z.ZodString;
    agent_id: z.ZodString;
    body: z.ZodString;
    message_type: z.ZodEnum<["message", "artifact", "system"]>;
    is_pinned: z.ZodDefault<z.ZodBoolean>;
    created_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    created_at: string;
    body: string;
    agent_id: string;
    project_id: string;
    message_type: "message" | "artifact" | "system";
    is_pinned: boolean;
}, {
    id: string;
    created_at: string;
    body: string;
    agent_id: string;
    project_id: string;
    message_type: "message" | "artifact" | "system";
    is_pinned?: boolean | undefined;
}>;
export type ProjectMessage = z.infer<typeof ProjectMessageSchema>;
export declare const CommitmentStatusSchema: z.ZodEnum<["pending", "resolved", "stalled", "cancelled"]>;
export type CommitmentStatus = z.infer<typeof CommitmentStatusSchema>;
export declare const CommitmentResolutionTypeSchema: z.ZodEnum<["artifact", "manual", "nudge_produced"]>;
export type CommitmentResolutionType = z.infer<typeof CommitmentResolutionTypeSchema>;
export declare const CommitmentSchema: z.ZodObject<{
    id: z.ZodString;
    tenant_id: z.ZodString;
    agent_id: z.ZodString;
    project_id: z.ZodNullable<z.ZodString>;
    description: z.ZodString;
    committed_at: z.ZodString;
    deadline_at: z.ZodNullable<z.ZodString>;
    status: z.ZodEnum<["pending", "resolved", "stalled", "cancelled"]>;
    resolution_type: z.ZodNullable<z.ZodEnum<["artifact", "manual", "nudge_produced"]>>;
    resolved_artifact_id: z.ZodNullable<z.ZodString>;
    resolved_at: z.ZodNullable<z.ZodString>;
    nudge_count: z.ZodDefault<z.ZodNumber>;
    last_nudge_at: z.ZodNullable<z.ZodString>;
    created_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    status: "pending" | "cancelled" | "resolved" | "stalled";
    id: string;
    tenant_id: string;
    created_at: string;
    agent_id: string;
    description: string;
    project_id: string | null;
    committed_at: string;
    deadline_at: string | null;
    resolution_type: "artifact" | "manual" | "nudge_produced" | null;
    resolved_artifact_id: string | null;
    resolved_at: string | null;
    nudge_count: number;
    last_nudge_at: string | null;
}, {
    status: "pending" | "cancelled" | "resolved" | "stalled";
    id: string;
    tenant_id: string;
    created_at: string;
    agent_id: string;
    description: string;
    project_id: string | null;
    committed_at: string;
    deadline_at: string | null;
    resolution_type: "artifact" | "manual" | "nudge_produced" | null;
    resolved_artifact_id: string | null;
    resolved_at: string | null;
    last_nudge_at: string | null;
    nudge_count?: number | undefined;
}>;
export type Commitment = z.infer<typeof CommitmentSchema>;
