// ============================================================================
// generate-registry.ts — Phase 1 Task 4.1.
//
// Builds `agents/registry.md` — Eleanor's routing directory per spec §5.2.1.
// Grouped: tier (H2) → department (H3) → agent line (`- {slug} — {role}`).
//
// Scope: 119 active agents that have a corresponding `.claude/agents/<slug>.md`
// file (excludes Shin Park, the human user).
//
// Always overwrites — generated file, not curated.
//
// CLI:
//   pnpm exec tsx <path>/generate-registry.ts                  # dry-run
//   pnpm exec tsx <path>/generate-registry.ts --apply          # write
//   pnpm exec tsx <path>/generate-registry.ts --verbose        # per-tier lines
//
// Plan ref: docs/superpowers/plans/.../...foundation-data-and-agents.md Task 4.1
// ============================================================================

import { config as loadEnv } from "dotenv";
import { existsSync } from "node:fs";
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { createClient } from "@supabase/supabase-js";

// ---------------------------------------------------------------------------
// Repo discovery + env load
// ---------------------------------------------------------------------------
function findRepoRoot(): string {
  let dir = process.cwd();
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, "pnpm-workspace.yaml"))) return dir;
    const parent = join(dir, "..");
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error(
    `cwd does not look like the headcount repo (no pnpm-workspace.yaml found from ${process.cwd()})`,
  );
}

const REPO_ROOT = findRepoRoot();
loadEnv({ path: join(REPO_ROOT, "apps", "orchestrator", ".env") });

const AGENTS_DIR = join(REPO_ROOT, ".claude", "agents");
const REGISTRY_PATH = join(REPO_ROOT, "agents", "registry.md");
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error(
    "Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in apps/orchestrator/.env",
  );
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// ---------------------------------------------------------------------------
// CLI args
// ---------------------------------------------------------------------------
const argv = process.argv.slice(2);
const APPLY = argv.includes("--apply");
const VERBOSE = argv.includes("--verbose");

// ---------------------------------------------------------------------------
// Slugify — must match the convention used by `.claude/agents/<slug>.md`
// ---------------------------------------------------------------------------
function slugify(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// ---------------------------------------------------------------------------
// Tier order + display
// ---------------------------------------------------------------------------
const TIER_ORDER = ["exec", "director", "manager", "associate", "intern", "bot"] as const;
type Tier = (typeof TIER_ORDER)[number];
const TIER_HEADING: Record<Tier, string> = {
  exec: "Exec",
  director: "Director",
  manager: "Manager",
  associate: "Associate",
  intern: "Intern",
  bot: "Bot",
};

// ---------------------------------------------------------------------------
// Header content (constant)
// ---------------------------------------------------------------------------
const FILE_HEADER = `# Onepark Digital — agent routing directory

<!-- Generated by apps/orchestrator/src/migrations/foundation/generate-registry.ts.
     Source of truth for Eleanor's routing decisions per spec §5.2.1.
     Regenerated whenever the agents table changes (Phase 4: nightly regen). -->

This is the routing graph for Eleanor's depth-aware delegation. To dispatch work to an agent, use the \`Agent\` tool with the agent's slug. Within each tier, agents are grouped by department; within each department, sorted alphabetically by slug.
`;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
interface AgentRow {
  id: string;
  name: string;
  role: string;
  tier: string;
  department: string | null;
}

interface Entry {
  slug: string;
  name: string;
  role: string;
  tier: string;
  department: string | null;
}

const NO_DEPT_KEY = "(no department)";

// ---------------------------------------------------------------------------
// Compute
// ---------------------------------------------------------------------------
function buildRegistry(entries: Entry[]): {
  body: string;
  tierCounts: Record<string, number>;
  departmentCount: number;
  nullDeptSlugs: string[];
} {
  // Group: tier -> department -> Entry[]
  const byTier = new Map<string, Map<string, Entry[]>>();
  const allDepartments = new Set<string>();
  const nullDeptSlugs: string[] = [];

  for (const e of entries) {
    if (!byTier.has(e.tier)) byTier.set(e.tier, new Map());
    const deptMap = byTier.get(e.tier)!;
    const deptKey = e.department ?? NO_DEPT_KEY;
    if (e.department == null) nullDeptSlugs.push(e.slug);
    if (!deptMap.has(deptKey)) deptMap.set(deptKey, []);
    deptMap.get(deptKey)!.push(e);
    if (e.department != null) allDepartments.add(e.department);
  }

  const tierCounts: Record<string, number> = {};
  const lines: string[] = [FILE_HEADER];

  for (const tier of TIER_ORDER) {
    const deptMap = byTier.get(tier);
    if (!deptMap || deptMap.size === 0) continue;

    const tierTotal = [...deptMap.values()].reduce((sum, list) => sum + list.length, 0);
    tierCounts[tier] = tierTotal;

    lines.push(`## ${TIER_HEADING[tier]}`);
    lines.push("");

    // Sort departments alphabetically; (no department) last
    const deptKeys = [...deptMap.keys()].sort((a, b) => {
      if (a === NO_DEPT_KEY) return 1;
      if (b === NO_DEPT_KEY) return -1;
      return a.localeCompare(b);
    });

    for (const dept of deptKeys) {
      lines.push(`### ${dept}`);
      lines.push("");
      const agents = deptMap.get(dept)!;
      agents.sort((a, b) => a.slug.localeCompare(b.slug));
      for (const a of agents) {
        lines.push(`- ${a.slug} — ${a.role}`);
      }
      lines.push("");
    }
  }

  // Strip trailing blank lines, then end with a single newline.
  let body = lines.join("\n").replace(/\n+$/g, "") + "\n";

  return {
    body,
    tierCounts,
    departmentCount: allDepartments.size,
    nullDeptSlugs,
  };
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
async function main(): Promise<void> {
  console.log("> generate-registry v1");
  console.log(`> Mode: ${APPLY ? "APPLY" : "DRY-RUN"}${APPLY ? "" : "  (use --apply to write)"}`);
  console.log(">");

  // Load agents
  console.log("> Loading active agents from Supabase...");
  const { data, error } = await supabase
    .from("agents")
    .select("id, name, role, tier, department")
    .eq("status", "active");
  if (error) throw new Error(`agents query failed: ${error.message}`);
  if (!data) throw new Error("no agents returned");

  const agents = data as AgentRow[];

  // Build the in-scope set: active agents that have a corresponding .md file
  const mdFiles = (await readdir(AGENTS_DIR)).filter((f) => f.endsWith(".md"));
  const mdSlugs = new Set(mdFiles.map((f) => f.replace(/\.md$/, "")));

  const entries: Entry[] = [];
  const dbActiveWithoutFile: string[] = [];
  for (const a of agents) {
    const slug = slugify(a.name);
    if (mdSlugs.has(slug)) {
      entries.push({ slug, name: a.name, role: a.role, tier: a.tier, department: a.department });
    } else {
      dbActiveWithoutFile.push(a.name);
    }
  }

  console.log(
    `  ${entries.length} agent${entries.length === 1 ? "" : "s"} in scope${
      dbActiveWithoutFile.length > 0
        ? ` (excluded ${dbActiveWithoutFile.length} active agent${
            dbActiveWithoutFile.length === 1 ? "" : "s"
          } with no .md file: ${dbActiveWithoutFile.join(", ")})`
        : ""
    }`,
  );

  // Pre-flight
  console.log("");
  console.log("> Pre-flight:");
  console.log(`  ✓ Repo root confirmed`);

  const agentsDir = join(REPO_ROOT, "agents");
  if (APPLY) {
    await mkdir(agentsDir, { recursive: true });
  } else if (!existsSync(agentsDir)) {
    throw new Error(`agents/ directory does not exist (and we are in DRY-RUN; use --apply to create)`);
  }
  console.log(`  ✓ agents/ directory exists`);

  // Compute
  console.log("");
  console.log("> Computing registry...");
  const { body, tierCounts, departmentCount, nullDeptSlugs } = buildRegistry(entries);

  const tierStr = TIER_ORDER.filter((t) => (tierCounts[t] ?? 0) > 0)
    .map((t) => `${t}=${tierCounts[t]}`)
    .join(" ");
  console.log(`  Tier distribution: ${tierStr}`);
  console.log(`  Departments: ${departmentCount} distinct`);
  console.log(
    `  Output: ${body.split("\n").length} lines, ${Buffer.byteLength(body, "utf8")} bytes`,
  );

  if (nullDeptSlugs.length > 0) {
    console.log(
      `  ⚠ ${nullDeptSlugs.length} agent${
        nullDeptSlugs.length === 1 ? "" : "s"
      } have no department: ${nullDeptSlugs.join(", ")}`,
    );
  }

  if (VERBOSE) {
    console.log("");
    console.log("--- registry preview (first 40 lines) ---");
    console.log(body.split("\n").slice(0, 40).join("\n"));
    console.log("--- end preview ---");
  }

  // Write
  if (APPLY) {
    console.log("");
    console.log("> Writing agents/registry.md...");
    await writeFile(REGISTRY_PATH, body, "utf8");
    console.log("  Written.");
  }

  console.log("");
  console.log("> Done.");
}

main().catch((e) => {
  console.error(`FATAL: ${(e as Error).message}`);
  process.exit(1);
});
